[package]
name = "anyrun-ha-assist"
version = "0.1.0"
edition = "2021"
description = "An anyrun plugin that lets you use Home Assistant's Assist."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
